# Generated by Django 5.0.4 on 2025-03-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userRegistration',
        ),
    ]
