# Generated by Django 5.0.4 on 2025-03-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='membership',
        ),
        migrations.DeleteModel(
            name='userRegistration',
        ),
    ]
